routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('routes','RouteController');
Route::resource('buses','BusController');
Route::resource('stops','StopController');
Route::resource('fares','FareController');
Route::resource('reservations','ReservationController');
Route::get('other', function(){
    return view('others');
})->name('other');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Stops.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Stops extends Model
{
    protected $fillable=['stop_name','description','time_from_prev','image'];

    public function routes()
    {
        return $this->belongsToMany('App\Route');
    }
}

app/Http/Controllers/StopController.php
<?php

namespace App\Http\Controllers;

use App\Stops;
use Illuminate\Http\Request;

class StopController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $all_stops = Stops::all();
        return view('stops.index',compact('all_stops'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $stop = new Stops();
        return view('stops.create', compact('stop'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'stop_name' => 'required|max:255|min:1',
        ]);
        $stop = new Stops();
        $stop->fill($request->only('stop_name','description'));
        $stop->save();
        return redirect()->route('stops.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $stop = Stops::find($id);
        return view('stops.edit', compact('stop'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'stop_name' => 'required|max:255|min:1',
        ]);
        $stop = Stops::find($id);
        $stop->fill($request->only('stop_name','description'));
        $stop->update();
        return redirect()->route('stops.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/stops/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <h3>Add New Stoppage</h3>
                <hr>
                <form action="{{ route('stops.store') }}" method="post">
                    @csrf()
                    @include('stops.form')
                </form>
            </div>
        </div>

    </div>
@endsection

resources/views/stops/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h3>Update :</h3>
                <form method="post" action="{{ route('stops.update', $stop->id)}}" >
                    @csrf()
                    {{ method_field('PUT')}}
                    @include('stops.form')
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/stops/form.blade.php
<div class="form-group">
    <label for="stop_name">Stoppage Name</label>
    <input type="text" class="form-control" name="stop_name" id="stop_name" value="{{ $stop->stop_name }}" required>
</div>
<div class="form-group">
    <label for="capacity">Capacity</label>
    <textarea name="description" id="" cols="30" rows="10" class="form-control">
        {!! $stop->description !!}
    </textarea>
</div>
<button type="submit" class="btn btn-primary">Submit</button>

resources/views/stops/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h3>List of Stops:</h3>
                <hr>
                <a href="{{ route('stops.create') }}">Add new Stop</a>
                <table class="table table-bordered">
                    <tr>
                        <th>Stoppage Name</th>
                        <th>Description</th>
                    </tr>
                    @foreach( $all_stops as $stop)
                        <tr>
                            <td>
                                {{ $stop->stop_name }} <br>
                                ( <a href="{{ Route('stops.edit', $stop->id ) }}" class="small">Update </a> )
                            </td>
                            <td>
                                {!! $stop->description !!}
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>
        </div>

    </div>
@endsection