routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('routes','RouteController');
Route::resource('buses','BusController');
Route::resource('stops','StopController');
Route::resource('fares','FareController');
Route::resource('reservations','ReservationController');
Route::get('other', function(){
    return view('others');
})->name('other');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Bus.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bus extends Model
{
    protected $fillable=[ 'bus_name','capacity'];

    public function routes()
    {
        return $this->belongsToMany('App\Route');
    }
}

app/Http/Controllers/BusController.php
<?php

namespace App\Http\Controllers;

use App\Bus;
use Illuminate\Http\Request;
use Illuminate\View\View;

class BusController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $all_buses = Bus::all();
        $bus = new Bus();
        return view('bus.index', compact('all_buses','bus'));
    }


    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'bus_name' => 'required|max:255|min:1',
        ]);
        $bus = new Bus();
        $bus->fill($request->only('bus_name','capacity'));
        $bus->save();
        return redirect()->route('buses.index');
    }



    public function edit($id)
    {
       $bus = Bus::find($id);
       return view('bus.edit', compact('bus'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'bus_name' => 'required|max:255|min:1',
        ]);
        $bus = Bus::find($id);
        $bus->fill($request->only('bus_name','capacity'));
        $bus->update();

        return redirect()->route('buses.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/bus/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h3>Update Bus Name & Capacity:</h3>
                <form method="post" action="{{ route('buses.update', $bus->id)}}" >
                    @csrf()
                    {{ method_field('PUT')}}
                    @include('bus.form')
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/bus/form.blade.php
<div class="form-group">
        <label for="bus">Bus Name</label>
        <input type="text" class="form-control" name="bus_name" id="bus" value="{{ $bus->bus_name }}" required>
    </div>
<div class="form-group">
    <label for="capacity">Capacity</label>
    <input type="text" class="form-control" name="capacity" id="capacity" value="{{ $bus->capacity }}" required>
</div>
    <button type="submit" class="btn btn-primary">Submit</button>

resources/views/bus/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h3>List of Available Buses:</h3>
                <table class="table table-bordered">
                    <tr>
                        <th>Bus Name</th>
                        <th>Capacity</th>
                        <th>Current Route</th>
                    </tr>
                    @foreach( $all_buses as $bus)
                        <tr>
                            <td>
                                {{ $bus->bus_name }} <br>
                               ( <a href="{{ Route('buses.edit', $bus->id ) }}" class="small">Update Bus Name</a> )
                            </td>
                            <td>{{ $bus->capacity }}</td>
                            <td></td>
                        </tr>
                    @endforeach
                </table>
            </div>
            <div class="col-md-4 border-left">
                <h3>Add New Bus</h3>
                <hr>
                <form action="{{ route('buses.store') }}" method="post">
                    @csrf()
                    @include('bus.form')
                </form>
            </div>
        </div>

    </div>
@endsection