routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('routes','RouteController');
Route::resource('buses','BusController');
Route::resource('stops','StopController');
Route::resource('fares','FareController');
Route::resource('reservations','ReservationController');
Route::get('other', function(){
    return view('others');
})->name('other');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Fare.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Fare extends Model
{
    protected $fillable=['start_id','destination_id','date','fare_amount'];
}

app/Http/Controllers/FareController.php
<?php

namespace App\Http\Controllers;

use App\Fare;
use App\Http\Resources\FareCollection as FareResource;
use Illuminate\Http\Request;

class FareController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $fares = Fare::orderBy('date')->get();
        return view('fare.index',compact('fares'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $fare = new Fare();
        return view('fare.create', compact('fare'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'start_id' => 'required',
            'destination_id' => 'required',
        ]);
        $fare = new Fare();
        $fare->fill($request->only('start_id','destination_id','fare_amount'));
//        $fare->date = date_format($request->input('date'), 'Y-m-d');
        $fare->date = date("Y-m-d", strtotime($request->input('date')));

        $fare->save();
        return redirect()->route('fares.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function api(Request $request)
    {
        $data = array();
        $date = date("Y-m-d", strtotime($request->input('date')));
        $fares = Fare::where('date',$date)->paginate();
        foreach( $fares as $fare){
            $fare->start_name = \App\Stops::find($fare->start_id)->stop_name;
            $fare->destination_name = \App\Stops::find($fare->destination_id)->stop_name;
        }

//        return response()->json($fares, 200);
        return new FareResource($fares);
    }
}

resources/views/fare/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <h3>Create New Fare</h3>
                <hr>
                <form action="{{ route('fares.store') }}" method="post">
                    @csrf()
                    @include('fare.form')
                </form>
            </div>
        </div>

    </div>
@endsection

resources/views/fare/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h3>Update :</h3>
                <form method="post" action="{{ route('fares.update', $fare->id)}}" >
                    @csrf()
                    {{ method_field('PUT')}}
                    @include('fare.form')
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/fare/form.blade.php
<div class="form-group">
    <label for="date">Date</label>
    <input type="date" name="date" value="{{ $fare->date }}" class="form-control">
</div>
<div class="form-group">
    <label for="start_id">Starts From</label>
    <select name="start_id" id="" class="form-control">
        @foreach(\App\Stops::all() as $stop)
            <option value="{{ $stop->id }}"
                    @if($stop->id == $fare->id) selected="selected9" @endif>{{ $stop->stop_name }}</option>
        @endforeach
    </select>
</div>
<div class="form-group">
    <label for="destination_id">Destination</label>
    <select name="destination_id" id="" class="form-control">
        @foreach(\App\Stops::all() as $stop)
            <option value="{{ $stop->id }}">{{ $stop->stop_name }}</option>
        @endforeach
    </select>
</div>
<div class="form-group">
    <label for="fair_amount">Amount</label>
    <input type="text" name="fare_amount" value="{{ $fare->fare_amount }}" class="form-control">
</div>

<button type="submit" class="btn btn-primary">Submit</button>

resources/views/fare/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h3>Fare Table</h3>
            <hr>
            <a class="small" href="{{ route('fares.create') }}">Add New Fare</a>

            <table class="table table-bordered">
                <tr>
                    <th>Date</th>
                    <th>From</th>
                    <th>To</th>
                    <th>Fare</th>
                </tr>
                @foreach($fares as $fare)
                    <tr>
                        <td>
                            {{ date('d M, y', strtotime($fare->date) )}}
                        </td>
                        <td>
                            {{ \App\Stops::find($fare->start_id)->stop_name }}
                        </td>
                        <td>
                            {{ \App\Stops::find($fare->destination_id)->stop_name }}
                        </td>
                        <td>
                            {{ $fare->fare_amount }}
                        </td>
                    </tr>
                @endforeach
            </table>
        </div>

    </div>
@endsection